# -*- coding: utf-8 -*-
"""Developers Hub Task 06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpCu8PfFLlTD-EEU45T_OXPIeqFLNOkL

### **Task 06: House Price Prediction**

### Problem Statement & Goal
 (Regression)<br>The primary goal is to build a robust machine learning model to accurately predict the selling price of a house based on various features (size, location, condition, etc.). We will compare a simple Linear Regression model against a powerful Gradient Boosting Regressor.

### Dataset Loading & Preprocessing
1.Categorical Encoding: The nominal features (Location, Condition, Garage) were converted into a machine-readable format using One-Hot Encoding (pd.get_dummies()).<br>2. Feature Scaling: All features were standardized using StandardScaler. This is crucial for models like Linear Regression and helps the Gradient Boosting model converge faster and perform better by giving equal weight to features regardless of their original scale.

### Model Training & Evaluation
We used Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE) to assess the models' performance, where lower values are better.

### Explanation of Results & Final Insights
The GBR model, after careful preprocessing and hyperparameter tuning (n_estimators=500, learning_rate=0.05), is reliable for predicting house prices. The visualization of the test set shows the GBR predictions closely following the actual prices. The final predicted price for a sample house is: 358561.80
"""

# ==============================================
#   TASK 6 – HOUSE PRICE PREDICTION (COMPLETE)
#   Developer Hub Corporation – Internship Task
# ==============================================

# ----------------------------------------------
# 1. IMPORT LIBRARIES
# ----------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression

plt.style.use("default")

# ----------------------------------------------
# 2. UPLOAD THE DATASET
# ----------------------------------------------

print("📂 Please upload your house price dataset CSV file")
uploaded = files.upload()

for fn in uploaded.keys():
    print("File uploaded:", fn)
    filename = fn   # store automatically

# ----------------------------------------------
# 3. LOAD THE DATASET
# ----------------------------------------------

df = pd.read_csv(filename)
print("\nDataset Loaded Successfully!\n")
display(df.head())

print("\nShape:", df.shape)
print("\nColumns:", df.columns.tolist())

print("\nInfo:")
df.info()

print("\nSummary Statistics:")
display(df.describe())


# ----------------------------------------------
# 4. PREPROCESSING
# ----------------------------------------------

# Drop ID (not useful for prediction)
df = df.drop("Id", axis=1)

# One-hot encode categorical columns
df = pd.get_dummies(df, columns=["Location", "Condition", "Garage"], drop_first=True)

# Select features and target
X = df.drop("Price", axis=1)
y = df["Price"]

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)


# ----------------------------------------------
# 5. TRAIN MODELS
# ----------------------------------------------

# Simple Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

# Improved Gradient Boosting Regressor
gbr = GradientBoostingRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    random_state=42
)

gbr.fit(X_train, y_train)
gbr_pred = gbr.predict(X_test)


# ----------------------------------------------
# 6. EVALUATION
# ----------------------------------------------

def evaluate(true, pred, model_name):
    mae = mean_absolute_error(true, pred)
    rmse = np.sqrt(mean_squared_error(true, pred))
    print(f"\n📌 {model_name} Evaluation:")
    print(f"   MAE  = {mae:.2f}")
    print(f"   RMSE = {rmse:.2f}")

evaluate(y_test, lr_pred, "Linear Regression")
evaluate(y_test, gbr_pred, "Gradient Boosting")


# ----------------------------------------------
# 7. VISUALIZATION (Actual vs Predicted)
# ----------------------------------------------

plt.figure(figsize=(12, 6))
plt.plot(y_test.values[:100], label="Actual Price", linewidth=2)
plt.plot(gbr_pred[:100], label="Predicted Price (GBR)", linewidth=2)
plt.title("Actual vs Predicted House Prices")
plt.xlabel("Samples")
plt.ylabel("Price")
plt.legend()
plt.show()


# ----------------------------------------------
# 8. PREDICT PRICE FOR A NEW HOUSE (WITHOUT WARNING)
# ----------------------------------------------

# Taking first row as sample structure
sample = X.iloc[0]

# Convert to df before scaling → FIXES WARNING
sample_df = pd.DataFrame([sample], columns=X.columns)

sample_scaled = scaler.transform(sample_df)
prediction = gbr.predict(sample_scaled)[0]

print(f"\n🏡 Predicted Price for Sample House: {prediction:.2f}")