# -*- coding: utf-8 -*-
"""Developer Hub Task 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VayGI54NyTD3z9N-ZliD6wAuvnQhFBxZ
"""

!pip install flask-cors

# Install required libraries in Colab (Ensure these lines run successfully)
!pip install flask google-genai pyngrok Flask-CORS

# Import the necessary libraries
import os
from flask import Flask, request, jsonify
from flask_cors import CORS # <--- This import should now work
from google import genai
from google.genai.errors import APIError
from pyngrok import ngrok

# --- Configuration ---
GEMINI_API_KEY = "AIzaSyA8ZOawT7zsXhw_82z2QjBrwLgw6zPmTu0"

# --- FLASK APP Setup ---
app = Flask(__name__)
# Crucial: Enable CORS to allow your local VS Code frontend to access this remote server
CORS(app)

# --- PROMPT ENGINEERING & SAFETY FILTERS ---
SYSTEM_PROMPT = """
You are a friendly, compassionate, and highly informative General Health Chatbot powered by Gemini.
Your primary goal is to provide clear, general, and easy-to-understand health information based on common knowledge.

***SAFETY AND GUIDELINE FILTER (STRICT):***
1.  **NEVER** provide a specific medical diagnosis (e.g., "You have strep throat").
2.  **NEVER** recommend or prescribe a specific treatment plan, dosage, or medication for a personal condition (e.g., "Take 500mg of Drug X twice a day").
3.  **ALWAYS** start your response with a clear, non-technical disclaimer: "⚠️ Please remember that I am an AI and not a doctor. This information is for general knowledge only and should not replace professional medical advice."
4.  **In all cases, but especially if a user describes symptoms or asks for personal advice,** explicitly advise them to consult a qualified healthcare professional (a doctor, pharmacist, or pediatrician).
5.  Keep your tone friendly, encouraging, and clear.
"""

# Initialize the Gemini client
try:
    client = genai.Client(api_key=GEMINI_API_KEY)
    print("Gemini client initialized.")
except Exception as e:
    print(f"Error initializing Gemini client: {e}")
    # If the key is invalid, the script will halt here.
    exit()

@app.route('/chat', methods=['POST'])
def chat():
    """Endpoint to handle user queries and get a response from Gemini."""
    try:
        data = request.get_json()
        user_query = data.get('query')

        if not user_query:
            return jsonify({'error': 'No query provided'}), 400

        # --- CORRECTION HERE: Combine the system prompt and user query into one string ---
        # This sends a single, well-engineered instruction to the model.
        full_prompt = SYSTEM_PROMPT + "\n\nUser's Question: " + user_query

        # Call the Gemini API using the plain string format for the contents
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            # The contents should be a list containing the text string(s)
            contents=[full_prompt],
            config={"temperature": 0.7}
        )

        return jsonify({'response': response.text})

    except APIError as e:
        return jsonify({'error': f'Gemini API Error: {e.message}'}), 500
    except Exception as e:
        print(f"Internal Server Error: {e}")
        return jsonify({'error': 'An unexpected error occurred on the server.'}), 500

# --- NGROK SETUP (To expose the Colab server to the internet) ---

PORT = 5000
# ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN") # Optional
public_url = ngrok.connect(PORT)

print(f"\n--- Colab Backend Running ---")
print(f"Flask App is running on port {PORT}")
print(f"PUBLIC URL for Frontend (use this in VS Code): {public_url}")
print("---------------------------\n")

# Run the Flask app
app.run(port=PORT, threaded=True)