# -*- coding: utf-8 -*-
"""Developer Hub Task 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBClaXnkIAsRTrB7HQLNoTLR7y1Q0ZL6

### **Task 01: Exploring & Visualizing Iris Dataset**

### **Problem Statement & Goal**
The objective of this task is to perform Exploratory Data Analysis (EDA) on the classic Iris flower dataset. This involves understanding the dataset's structure, identifying the distribution of its features, and visualizing the relationships between different flower measurements to see how the three species are differentiated.

### **Dataset Loading & Preprocessing**
The Iris dataset contains 150 samples across four numerical features (sepal_length, sepal_width, petal_length, petal_width) and one categorical target variable (species). As there are no missing values and all feature columns are numeric, minimal preprocessing is required, making it ideal for immediate visualization.

### **Data Visualization & Exploration**
1.Scatter Plot: The plot of Sepal Length vs. Sepal Width shows that the Iris-setosa species is distinctly clustered and easily separated from the other two species. Versicolor and Virginica show some overlap.<br>2.  Histograms: The feature distributions are generally normal, though Petal Length and Petal Width show distinct, multi-modal distributions corresponding to the three species.<br>3. Box Plots: These plots help identify potential outliers. A few mild outliers are visible in the sepal_width feature, particularly for the Setosa species.

### **Explanation of Results & Final Insights**
The EDA confirms the dataset's suitability for classification tasks. The most discriminating features appear to be Petal Length and Petal Width, as seen in the pairplot, suggesting that these are the most reliable measurements for accurately distinguishing between the three Iris species.
"""

# ----------------------------------------
# TASK 1 – Exploring & Visualizing Iris Dataset
# ----------------------------------------

# Importing libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# For clear plots
plt.style.use("default")

# ----------------------------------------
# 1. Load the Iris dataset
# ----------------------------------------
iris = sns.load_dataset("iris")   # Loading directly from seaborn

# ----------------------------------------
# 2. Print basic information
# ----------------------------------------

print("Shape of dataset:", iris.shape)
print("\nColumn names:", iris.columns.tolist())

print("\nFirst 5 rows:")
display(iris.head())

print("\nDataset Info:")
iris.info()

print("\nSummary Statistics:")
display(iris.describe())

# ----------------------------------------
# 3. Visualizations
# ----------------------------------------

# Scatter Plot – Relationship between features
plt.figure(figsize=(7,5))
sns.scatterplot(data=iris, x="sepal_length", y="sepal_width", hue="species")
plt.title("Scatter Plot: Sepal Length vs Sepal Width")
plt.show()

# Histogram – Distribution of values
iris.hist(figsize=(10,8), bins=15)
plt.suptitle("Histograms of Iris Features", y=1.02)
plt.show()

# Box Plots – Identify Outliers
plt.figure(figsize=(10,6))
sns.boxplot(data=iris)
plt.title("Box Plot of Iris Dataset Features")
plt.show()

# Pairplot – Bonus Visualization
sns.pairplot(iris, hue="species")
plt.suptitle("Pairplot of Iris Dataset", y=1.02)
plt.show()